<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3iFfYLhService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.3iFfYLh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3iFfYLh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'faction' => ['privates', '.errored..service_locator.3iFfYLh.App\\Entity\\Faction', NULL, 'Cannot autowire service ".service_locator.3iFfYLh": it needs an instance of "App\\Entity\\Faction" but this type has been excluded in "config/services.yaml".'],
            'imageResizer' => ['privates', 'App\\Service\\ImageResizerService', 'getImageResizerServiceService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'em' => '?',
            'faction' => 'App\\Entity\\Faction',
            'imageResizer' => 'App\\Service\\ImageResizerService',
            'slugger' => '?',
        ]);
    }
}
