<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V7U0tqLService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.v7U0tqL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v7U0tqL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'continent' => ['privates', '.errored..service_locator.v7U0tqL.App\\Entity\\Continent', NULL, 'Cannot autowire service ".service_locator.v7U0tqL": it needs an instance of "App\\Entity\\Continent" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'continent' => 'App\\Entity\\Continent',
            'em' => '?',
        ]);
    }
}
