<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MNIXpgfService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.MNIXpgf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MNIXpgf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'city' => ['privates', '.errored..service_locator.MNIXpgf.App\\Entity\\City', NULL, 'Cannot autowire service ".service_locator.MNIXpgf": it needs an instance of "App\\Entity\\City" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'imageResizer' => ['privates', 'App\\Service\\ImageResizerService', 'getImageResizerServiceService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'city' => 'App\\Entity\\City',
            'em' => '?',
            'imageResizer' => 'App\\Service\\ImageResizerService',
            'slugger' => '?',
        ]);
    }
}
