<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SekaUHGService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.SekaUHG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SekaUHG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'raceRepo' => ['privates', 'App\\Repository\\RaceRepository', 'getRaceRepositoryService', true],
            'worldRepo' => ['privates', 'App\\Repository\\WorldRepository', 'getWorldRepositoryService', true],
        ], [
            'raceRepo' => 'App\\Repository\\RaceRepository',
            'worldRepo' => 'App\\Repository\\WorldRepository',
        ]);
    }
}
