<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Iqam8taService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Iqam8ta' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Iqam8ta'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'faction' => ['privates', '.errored..service_locator.Iqam8ta.App\\Entity\\Faction', NULL, 'Cannot autowire service ".service_locator.Iqam8ta": it needs an instance of "App\\Entity\\Faction" but this type has been excluded in "config/services.yaml".'],
        ], [
            'faction' => 'App\\Entity\\Faction',
        ]);
    }
}
