<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H61EYService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator._H61E_Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._H61E_Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'capacity' => ['privates', '.errored..service_locator._H61E_Y.App\\Entity\\Capacity', NULL, 'Cannot autowire service ".service_locator._H61E_Y": it needs an instance of "App\\Entity\\Capacity" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'capacity' => 'App\\Entity\\Capacity',
            'em' => '?',
        ]);
    }
}
