<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G5Vf6e6Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.g5Vf6e6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g5Vf6e6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'world' => ['privates', '.errored..service_locator.g5Vf6e6.App\\Entity\\World', NULL, 'Cannot autowire service ".service_locator.g5Vf6e6": it needs an instance of "App\\Entity\\World" but this type has been excluded in "config/services.yaml".'],
        ], [
            'world' => 'App\\Entity\\World',
        ]);
    }
}
