<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BeTQNY6Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.BeTQNY6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BeTQNY6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'capacity' => ['privates', '.errored..service_locator.BeTQNY6.App\\Entity\\Capacity', NULL, 'Cannot autowire service ".service_locator.BeTQNY6": it needs an instance of "App\\Entity\\Capacity" but this type has been excluded in "config/services.yaml".'],
        ], [
            'capacity' => 'App\\Entity\\Capacity',
        ]);
    }
}
