<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9VSH8DOService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.9VSH8DO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9VSH8DO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'race' => ['privates', '.errored..service_locator.9VSH8DO.App\\Entity\\Race', NULL, 'Cannot autowire service ".service_locator.9VSH8DO": it needs an instance of "App\\Entity\\Race" but this type has been excluded in "config/services.yaml".'],
        ], [
            'race' => 'App\\Entity\\Race',
        ]);
    }
}
