<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3hGYyGRService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.3hGYyGR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3hGYyGR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'hero' => ['privates', '.errored..service_locator.3hGYyGR.App\\Entity\\Hero', NULL, 'Cannot autowire service ".service_locator.3hGYyGR": it needs an instance of "App\\Entity\\Hero" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'hero' => 'App\\Entity\\Hero',
        ]);
    }
}
