<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContinentRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ContinentRepository' shared autowired service.
     *
     * @return \App\Repository\ContinentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ContinentRepository'] = new \App\Repository\ContinentRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
