<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCapacity2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator._H61E_Y.App\Entity\Capacity' shared service.
     *
     * @return \App\Entity\Capacity
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._H61E_Y": it needs an instance of "App\\Entity\\Capacity" but this type has been excluded in "config/services.yaml".');
    }
}
