<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContinentTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ContinentType' shared autowired service.
     *
     * @return \App\Form\ContinentType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ContinentType'] = new \App\Form\ContinentType();
    }
}
