<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDomain3Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.dYbunHf.App\Entity\Domain' shared service.
     *
     * @return \App\Entity\Domain
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.dYbunHf": it needs an instance of "App\\Entity\\Domain" but this type has been excluded in "config/services.yaml".');
    }
}
