<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFactionControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\FactionController' shared autowired service.
     *
     * @return \App\Controller\FactionController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\FactionController'] = $instance = new \App\Controller\FactionController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\FactionController', $container));

        return $instance;
    }
}
