<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuildControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\GuildController' shared autowired service.
     *
     * @return \App\Controller\GuildController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\GuildController'] = $instance = new \App\Controller\GuildController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\GuildController', $container));

        return $instance;
    }
}
