<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageResizerServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\ImageResizerService' shared autowired service.
     *
     * @return \App\Service\ImageResizerService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\ImageResizerService'] = new \App\Service\ImageResizerService();
    }
}
