<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorldTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\WorldType' shared autowired service.
     *
     * @return \App\Form\WorldType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\WorldType'] = new \App\Form\WorldType();
    }
}
