<?php

namespace ContainerQiz6J7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorldRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\WorldRepository' shared autowired service.
     *
     * @return \App\Repository\WorldRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\WorldRepository'] = new \App\Repository\WorldRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
