security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\LoginFormAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_index
                enable_csrf: true
            logout:
                path: app_logout
            custom_authenticator: App\Security\LoginFormAuthenticator
            access_denied_url: app_login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }         # ✅ page d'accueil accessible sans être connecté
        - { path: ^/, roles: ROLE_USER }              # ✅ tout le reste nécessite la connexion

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

        firewalls:
            main:
                lazy: true
                provider: users_in_memory
                custom_authenticator: App\Security\LoginFormAuthenticator
                logout:
                    path: app_logout
