-- MySQL Script generated by MySQL Workbench
-- Tue Mar 11 09:48:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Project_Fantasia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Project_Fantasia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Project_Fantasia` DEFAULT CHARACTER SET utf8 ;
USE `Project_Fantasia` ;

-- -----------------------------------------------------
-- Table `Project_Fantasia`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `role` JSON NULL,
  `Profileimage` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Faction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Faction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Type` VARCHAR(255) NULL,
  `Regime` VARCHAR(255) NULL,
  `Image` VARCHAR(255) NULL,
  `Dirigeant` INT NULL,
  `Description` TEXT NULL,
  `emblemimage` VARCHAR(255) NULL,
  `Couleur` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `Capital` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`World`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`World` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Continent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Continent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Description` TEXT NULL,
  `Imagecontinent` VARCHAR(255) NULL,
  `carte` VARCHAR(255) NULL,
  `Continentcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`World_has_Continent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`World_has_Continent` (
  `World_id` INT NOT NULL,
  `Continent_id` INT NOT NULL,
  PRIMARY KEY (`World_id`, `Continent_id`),
  INDEX `fk_World_has_Continent_Continent1_idx` (`Continent_id` ASC) VISIBLE,
  INDEX `fk_World_has_Continent_World1_idx` (`World_id` ASC) VISIBLE,
  CONSTRAINT `fk_World_has_Continent_World1`
    FOREIGN KEY (`World_id`)
    REFERENCES `Project_Fantasia`.`World` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_World_has_Continent_Continent1`
    FOREIGN KEY (`Continent_id`)
    REFERENCES `Project_Fantasia`.`Continent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Visibility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Visibility` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `visibility` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Guild`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Guild` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Type` VARCHAR(255) NULL,
  `Image` VARCHAR(255) NULL,
  `Description` TEXT NULL,
  `Dirigeant` INT NULL,
  `Visibility_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Guild_Visibilité1_idx` (`Visibility_id` ASC) VISIBLE,
  CONSTRAINT `fk_Guild_Visibilité1`
    FOREIGN KEY (`Visibility_id`)
    REFERENCES `Project_Fantasia`.`Visibility` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`User_has_World`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`User_has_World` (
  `User_id` INT NOT NULL,
  `World_id` INT NOT NULL,
  `role` TINYINT NOT NULL,
  PRIMARY KEY (`User_id`, `World_id`),
  INDEX `fk_User_has_World_World1_idx` (`World_id` ASC) VISIBLE,
  INDEX `fk_User_has_World_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_World_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `Project_Fantasia`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_World_World1`
    FOREIGN KEY (`World_id`)
    REFERENCES `Project_Fantasia`.`World` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Faction_has_Continent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Faction_has_Continent` (
  `Faction_id` INT NOT NULL,
  `Continent_id` INT NOT NULL,
  PRIMARY KEY (`Faction_id`, `Continent_id`),
  INDEX `fk_Faction_has_Continent_Continent1_idx` (`Continent_id` ASC) VISIBLE,
  INDEX `fk_Faction_has_Continent_Faction1_idx` (`Faction_id` ASC) VISIBLE,
  CONSTRAINT `fk_Faction_has_Continent_Faction1`
    FOREIGN KEY (`Faction_id`)
    REFERENCES `Project_Fantasia`.`Faction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Faction_has_Continent_Continent1`
    FOREIGN KEY (`Continent_id`)
    REFERENCES `Project_Fantasia`.`Continent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Faction_has_Guild`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Faction_has_Guild` (
  `Faction_id` INT NOT NULL,
  `Guild_id` INT NOT NULL,
  PRIMARY KEY (`Faction_id`, `Guild_id`),
  INDEX `fk_Faction_has_Guild_Guild1_idx` (`Guild_id` ASC) VISIBLE,
  INDEX `fk_Faction_has_Guild_Faction1_idx` (`Faction_id` ASC) VISIBLE,
  CONSTRAINT `fk_Faction_has_Guild_Faction1`
    FOREIGN KEY (`Faction_id`)
    REFERENCES `Project_Fantasia`.`Faction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Faction_has_Guild_Guild1`
    FOREIGN KEY (`Guild_id`)
    REFERENCES `Project_Fantasia`.`Guild` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Continent_has_Guild`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Continent_has_Guild` (
  `Continent_id` INT NOT NULL,
  `Guild_id` INT NOT NULL,
  PRIMARY KEY (`Continent_id`, `Guild_id`),
  INDEX `fk_Continent_has_Guild_Guild1_idx` (`Guild_id` ASC) VISIBLE,
  INDEX `fk_Continent_has_Guild_Continent1_idx` (`Continent_id` ASC) VISIBLE,
  CONSTRAINT `fk_Continent_has_Guild_Continent1`
    FOREIGN KEY (`Continent_id`)
    REFERENCES `Project_Fantasia`.`Continent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Continent_has_Guild_Guild1`
    FOREIGN KEY (`Guild_id`)
    REFERENCES `Project_Fantasia`.`Guild` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Hero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Hero` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Age` VARCHAR(255) NULL,
  `Taille` VARCHAR(255) NULL,
  `Image` VARCHAR(255) NULL,
  `Description` TEXT NULL,
  `Fonction` VARCHAR(255) NULL,
  `Domaine` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Hero_has_Guild`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Hero_has_Guild` (
  `Hero_id` INT NOT NULL,
  `Guild_id` INT NOT NULL,
  PRIMARY KEY (`Hero_id`, `Guild_id`),
  INDEX `fk_Hero_has_Guild_Guild1_idx` (`Guild_id` ASC) VISIBLE,
  INDEX `fk_Hero_has_Guild_Hero1_idx` (`Hero_id` ASC) VISIBLE,
  CONSTRAINT `fk_Hero_has_Guild_Hero1`
    FOREIGN KEY (`Hero_id`)
    REFERENCES `Project_Fantasia`.`Hero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hero_has_Guild_Guild1`
    FOREIGN KEY (`Guild_id`)
    REFERENCES `Project_Fantasia`.`Guild` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Hero_has_Faction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Hero_has_Faction` (
  `Hero_id` INT NOT NULL,
  `Faction_id` INT NOT NULL,
  PRIMARY KEY (`Hero_id`, `Faction_id`),
  INDEX `fk_Hero_has_Faction_Faction1_idx` (`Faction_id` ASC) VISIBLE,
  INDEX `fk_Hero_has_Faction_Hero1_idx` (`Hero_id` ASC) VISIBLE,
  CONSTRAINT `fk_Hero_has_Faction_Hero1`
    FOREIGN KEY (`Hero_id`)
    REFERENCES `Project_Fantasia`.`Hero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hero_has_Faction_Faction1`
    FOREIGN KEY (`Faction_id`)
    REFERENCES `Project_Fantasia`.`Faction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Hero_has_Continent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Hero_has_Continent` (
  `Hero_id` INT NOT NULL,
  `Continent_id` INT NOT NULL,
  PRIMARY KEY (`Hero_id`, `Continent_id`),
  INDEX `fk_Hero_has_Continent_Continent1_idx` (`Continent_id` ASC) VISIBLE,
  INDEX `fk_Hero_has_Continent_Hero1_idx` (`Hero_id` ASC) VISIBLE,
  CONSTRAINT `fk_Hero_has_Continent_Hero1`
    FOREIGN KEY (`Hero_id`)
    REFERENCES `Project_Fantasia`.`Hero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hero_has_Continent_Continent1`
    FOREIGN KEY (`Continent_id`)
    REFERENCES `Project_Fantasia`.`Continent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`World_has_Hero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`World_has_Hero` (
  `World_id` INT NOT NULL,
  `Hero_id` INT NOT NULL,
  PRIMARY KEY (`World_id`, `Hero_id`),
  INDEX `fk_World_has_Hero_Hero1_idx` (`Hero_id` ASC) VISIBLE,
  INDEX `fk_World_has_Hero_World1_idx` (`World_id` ASC) VISIBLE,
  CONSTRAINT `fk_World_has_Hero_World1`
    FOREIGN KEY (`World_id`)
    REFERENCES `Project_Fantasia`.`World` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_World_has_Hero_Hero1`
    FOREIGN KEY (`Hero_id`)
    REFERENCES `Project_Fantasia`.`Hero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`World_has_Guild`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`World_has_Guild` (
  `World_id` INT NOT NULL,
  `Guild_id` INT NOT NULL,
  PRIMARY KEY (`World_id`, `Guild_id`),
  INDEX `fk_World_has_Guild_Guild1_idx` (`Guild_id` ASC) VISIBLE,
  INDEX `fk_World_has_Guild_World1_idx` (`World_id` ASC) VISIBLE,
  CONSTRAINT `fk_World_has_Guild_World1`
    FOREIGN KEY (`World_id`)
    REFERENCES `Project_Fantasia`.`World` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_World_has_Guild_Guild1`
    FOREIGN KEY (`Guild_id`)
    REFERENCES `Project_Fantasia`.`Guild` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`World_has_Faction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`World_has_Faction` (
  `World_id` INT NOT NULL,
  `Faction_id` INT NOT NULL,
  PRIMARY KEY (`World_id`, `Faction_id`),
  INDEX `fk_World_has_Faction_Faction1_idx` (`Faction_id` ASC) VISIBLE,
  INDEX `fk_World_has_Faction_World1_idx` (`World_id` ASC) VISIBLE,
  CONSTRAINT `fk_World_has_Faction_World1`
    FOREIGN KEY (`World_id`)
    REFERENCES `Project_Fantasia`.`World` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_World_has_Faction_Faction1`
    FOREIGN KEY (`Faction_id`)
    REFERENCES `Project_Fantasia`.`Faction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Domaine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Domaine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Type` VARCHAR(255) NULL,
  `Domaine` VARCHAR(255) NULL,
  `Image` VARCHAR(255) NULL,
  `Description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`capacity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`capacity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(255) NULL,
  `Domain` VARCHAR(255) NULL,
  `Image` VARCHAR(255) NULL,
  `Description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`capacity_has_Domaine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`capacity_has_Domaine` (
  `capacity_id` INT NOT NULL,
  `Domaine_id` INT NOT NULL,
  PRIMARY KEY (`capacity_id`, `Domaine_id`),
  INDEX `fk_capacity_has_Domaine_Domaine1_idx` (`Domaine_id` ASC) VISIBLE,
  INDEX `fk_capacity_has_Domaine_capacity1_idx` (`capacity_id` ASC) VISIBLE,
  CONSTRAINT `fk_capacity_has_Domaine_capacity1`
    FOREIGN KEY (`capacity_id`)
    REFERENCES `Project_Fantasia`.`capacity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_capacity_has_Domaine_Domaine1`
    FOREIGN KEY (`Domaine_id`)
    REFERENCES `Project_Fantasia`.`Domaine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Domaine_has_Hero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Domaine_has_Hero` (
  `Domaine_id` INT NOT NULL,
  `Hero_id` INT NOT NULL,
  PRIMARY KEY (`Domaine_id`, `Hero_id`),
  INDEX `fk_Domaine_has_Hero_Hero1_idx` (`Hero_id` ASC) VISIBLE,
  INDEX `fk_Domaine_has_Hero_Domaine1_idx` (`Domaine_id` ASC) VISIBLE,
  CONSTRAINT `fk_Domaine_has_Hero_Domaine1`
    FOREIGN KEY (`Domaine_id`)
    REFERENCES `Project_Fantasia`.`Domaine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Domaine_has_Hero_Hero1`
    FOREIGN KEY (`Hero_id`)
    REFERENCES `Project_Fantasia`.`Hero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`World_has_Domaine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`World_has_Domaine` (
  `World_id` INT NOT NULL,
  `Domaine_id` INT NOT NULL,
  PRIMARY KEY (`World_id`, `Domaine_id`),
  INDEX `fk_World_has_Domaine_Domaine1_idx` (`Domaine_id` ASC) VISIBLE,
  INDEX `fk_World_has_Domaine_World1_idx` (`World_id` ASC) VISIBLE,
  CONSTRAINT `fk_World_has_Domaine_World1`
    FOREIGN KEY (`World_id`)
    REFERENCES `Project_Fantasia`.`World` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_World_has_Domaine_Domaine1`
    FOREIGN KEY (`Domaine_id`)
    REFERENCES `Project_Fantasia`.`Domaine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`World_has_capacity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`World_has_capacity` (
  `World_id` INT NOT NULL,
  `capacity_id` INT NOT NULL,
  PRIMARY KEY (`World_id`, `capacity_id`),
  INDEX `fk_World_has_capacity_capacity1_idx` (`capacity_id` ASC) VISIBLE,
  INDEX `fk_World_has_capacity_World1_idx` (`World_id` ASC) VISIBLE,
  CONSTRAINT `fk_World_has_capacity_World1`
    FOREIGN KEY (`World_id`)
    REFERENCES `Project_Fantasia`.`World` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_World_has_capacity_capacity1`
    FOREIGN KEY (`capacity_id`)
    REFERENCES `Project_Fantasia`.`capacity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Race`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Race` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Image` VARCHAR(255) NULL,
  `Description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Race_has_Hero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Race_has_Hero` (
  `Race_id` INT NOT NULL,
  `Hero_id` INT NOT NULL,
  PRIMARY KEY (`Race_id`, `Hero_id`),
  INDEX `fk_Race_has_Hero_Hero1_idx` (`Hero_id` ASC) VISIBLE,
  INDEX `fk_Race_has_Hero_Race1_idx` (`Race_id` ASC) VISIBLE,
  CONSTRAINT `fk_Race_has_Hero_Race1`
    FOREIGN KEY (`Race_id`)
    REFERENCES `Project_Fantasia`.`Race` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Race_has_Hero_Hero1`
    FOREIGN KEY (`Hero_id`)
    REFERENCES `Project_Fantasia`.`Hero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Race_has_World`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Race_has_World` (
  `Race_id` INT NOT NULL,
  `World_id` INT NOT NULL,
  PRIMARY KEY (`Race_id`, `World_id`),
  INDEX `fk_Race_has_World_World1_idx` (`World_id` ASC) VISIBLE,
  INDEX `fk_Race_has_World_Race1_idx` (`Race_id` ASC) VISIBLE,
  CONSTRAINT `fk_Race_has_World_Race1`
    FOREIGN KEY (`Race_id`)
    REFERENCES `Project_Fantasia`.`Race` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Race_has_World_World1`
    FOREIGN KEY (`World_id`)
    REFERENCES `Project_Fantasia`.`World` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Race_has_Domaine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Race_has_Domaine` (
  `Race_id` INT NOT NULL,
  `Domaine_id` INT NOT NULL,
  PRIMARY KEY (`Race_id`, `Domaine_id`),
  INDEX `fk_Race_has_Domaine_Domaine1_idx` (`Domaine_id` ASC) VISIBLE,
  INDEX `fk_Race_has_Domaine_Race1_idx` (`Race_id` ASC) VISIBLE,
  CONSTRAINT `fk_Race_has_Domaine_Race1`
    FOREIGN KEY (`Race_id`)
    REFERENCES `Project_Fantasia`.`Race` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Race_has_Domaine_Domaine1`
    FOREIGN KEY (`Domaine_id`)
    REFERENCES `Project_Fantasia`.`Domaine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(255) NULL,
  `Image` VARCHAR(255) NULL,
  `Description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Hero_has_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Hero_has_city` (
  `Hero_id` INT NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`Hero_id`, `city_id`),
  INDEX `fk_Hero_has_city_city1_idx` (`city_id` ASC) VISIBLE,
  INDEX `fk_Hero_has_city_Hero1_idx` (`Hero_id` ASC) VISIBLE,
  CONSTRAINT `fk_Hero_has_city_Hero1`
    FOREIGN KEY (`Hero_id`)
    REFERENCES `Project_Fantasia`.`Hero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hero_has_city_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `Project_Fantasia`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`Faction_has_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`Faction_has_city` (
  `Faction_id` INT NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`Faction_id`, `city_id`),
  INDEX `fk_Faction_has_city_city1_idx` (`city_id` ASC) VISIBLE,
  INDEX `fk_Faction_has_city_Faction1_idx` (`Faction_id` ASC) VISIBLE,
  CONSTRAINT `fk_Faction_has_city_Faction1`
    FOREIGN KEY (`Faction_id`)
    REFERENCES `Project_Fantasia`.`Faction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Faction_has_city_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `Project_Fantasia`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_Fantasia`.`World_has_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project_Fantasia`.`World_has_city` (
  `World_id` INT NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`World_id`, `city_id`),
  INDEX `fk_World_has_city_city1_idx` (`city_id` ASC) VISIBLE,
  INDEX `fk_World_has_city_World1_idx` (`World_id` ASC) VISIBLE,
  CONSTRAINT `fk_World_has_city_World1`
    FOREIGN KEY (`World_id`)
    REFERENCES `Project_Fantasia`.`World` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_World_has_city_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `Project_Fantasia`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
