<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Capacity__CLASSMETADATA__' => 0,
'App__Entity__City__CLASSMETADATA__' => 1,
'App__Entity__Continent__CLASSMETADATA__' => 2,
'App__Entity__Domain__CLASSMETADATA__' => 3,
'App__Entity__Faction__CLASSMETADATA__' => 4,
'App__Entity__Guild__CLASSMETADATA__' => 5,
'App__Entity__Hero__CLASSMETADATA__' => 6,
'App__Entity__Race__CLASSMETADATA__' => 7,
'App__Entity__World__CLASSMETADATA__' => 8,
'App__Entity__Visibility__CLASSMETADATA__' => 9,
'App__Entity__User__CLASSMETADATA__' => 10,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinTableMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinTableMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Capacity',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\CapacityRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Name' => $o[2],
                        'Type' => $o[3],
                        'Image_Capacity' => $o[4],
                        'Description' => $o[5],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'Name',
                        'type' => 'Type',
                        'image_capacity' => 'Image_Capacity',
                        'description' => 'Description',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Name' => 'name',
                        'Type' => 'type',
                        'Image_Capacity' => 'image_capacity',
                        'Description' => 'description',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'capacity',
                    ],
                ],
                'associationMappings' => [
                    [
                        'Domain' => $o[6],
                        'Capacity_world' => $o[10],
                    ],
                ],
                'idGenerator' => [
                    $o[12],
                ],
                'name' => [
                    'App\\Entity\\Capacity',
                    7 => 'capacity_domain',
                    'capacity_id',
                    'domain_id',
                    11 => 'capacity_world_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'text',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Name',
                    'Type',
                    'Image_Capacity',
                    'Description',
                ],
                'columnName' => [
                    1 => 'id',
                    'name',
                    'type',
                    'image_capacity',
                    'description',
                ],
                'length' => [
                    2 => 255,
                    255,
                    255,
                ],
                'nullable' => [
                    3 => true,
                    true,
                    true,
                    11 => false,
                ],
                'fetch' => [
                    6 => 2,
                    10 => 2,
                ],
                'isOnDeleteCascade' => [
                    6 => true,
                ],
                'sourceEntity' => [
                    6 => 'App\\Entity\\Capacity',
                    10 => 'App\\Entity\\Capacity',
                ],
                'inversedBy' => [
                    6 => 'capacities',
                    10 => 'World_Capacity',
                ],
                'joinTable' => [
                    6 => $o[7],
                ],
                'joinTableColumns' => [
                    6 => [
                        'capacity_id',
                        'domain_id',
                    ],
                ],
                'relationToSourceKeyColumns' => [
                    6 => [
                        'capacity_id' => 'id',
                    ],
                ],
                'relationToTargetKeyColumns' => [
                    6 => [
                        'domain_id' => 'id',
                    ],
                ],
                'joinColumns' => [
                    7 => [
                        $o[8],
                    ],
                    10 => [
                        $o[11],
                    ],
                ],
                'inverseJoinColumns' => [
                    7 => [
                        $o[9],
                    ],
                ],
                'onDelete' => [
                    8 => 'CASCADE',
                    'CASCADE',
                ],
                'referencedColumnName' => [
                    8 => 'id',
                    'id',
                    11 => 'id',
                ],
                'sourceToTargetKeyColumns' => [
                    10 => [
                        'capacity_world_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    10 => [
                        'id' => 'capacity_world_id',
                    ],
                ],
                'joinColumnFieldNames' => [
                    10 => [
                        'capacity_world_id' => 'capacity_world_id',
                    ],
                ],
                'deferrable' => [
                    11 => false,
                ],
                'unique' => [
                    11 => false,
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    6 => 'Domain',
                    10 => 'Capacity_world',
                ],
                'targetEntity' => [
                    6 => 'App\\Entity\\Domain',
                    10 => 'App\\Entity\\World',
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinTableMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinTableMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\City',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\CityRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Name' => $o[2],
                        'Image_City' => $o[3],
                        'Description' => $o[4],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'Name',
                        'image_city' => 'Image_City',
                        'description' => 'Description',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Name' => 'name',
                        'Image_City' => 'image_city',
                        'Description' => 'description',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'city',
                    ],
                ],
                'associationMappings' => [
                    [
                        'City_Hero' => $o[5],
                        'City_Faction' => $o[6],
                        'City_World' => $o[10],
                    ],
                ],
                'idGenerator' => [
                    $o[12],
                ],
                'name' => [
                    'App\\Entity\\City',
                    7 => 'faction_city',
                    'city_id',
                    'faction_id',
                    11 => 'city_world_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'text',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Name',
                    'Image_City',
                    'Description',
                ],
                'columnName' => [
                    1 => 'id',
                    'name',
                    'image_city',
                    'description',
                ],
                'length' => [
                    2 => 255,
                    255,
                ],
                'nullable' => [
                    3 => true,
                    true,
                    11 => false,
                ],
                'fetch' => [
                    5 => 2,
                    2,
                    10 => 2,
                ],
                'sourceEntity' => [
                    5 => 'App\\Entity\\City',
                    'App\\Entity\\City',
                    10 => 'App\\Entity\\City',
                ],
                'mappedBy' => [
                    5 => 'Hero_City',
                ],
                'isOnDeleteCascade' => [
                    6 => true,
                ],
                'inversedBy' => [
                    6 => 'Faction_City',
                    10 => 'World_City',
                ],
                'joinTable' => [
                    6 => $o[7],
                ],
                'joinTableColumns' => [
                    6 => [
                        'city_id',
                        'faction_id',
                    ],
                ],
                'relationToSourceKeyColumns' => [
                    6 => [
                        'city_id' => 'id',
                    ],
                ],
                'relationToTargetKeyColumns' => [
                    6 => [
                        'faction_id' => 'id',
                    ],
                ],
                'joinColumns' => [
                    7 => [
                        $o[8],
                    ],
                    10 => [
                        $o[11],
                    ],
                ],
                'inverseJoinColumns' => [
                    7 => [
                        $o[9],
                    ],
                ],
                'onDelete' => [
                    8 => 'CASCADE',
                    'CASCADE',
                ],
                'referencedColumnName' => [
                    8 => 'id',
                    'id',
                    11 => 'id',
                ],
                'sourceToTargetKeyColumns' => [
                    10 => [
                        'city_world_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    10 => [
                        'id' => 'city_world_id',
                    ],
                ],
                'joinColumnFieldNames' => [
                    10 => [
                        'city_world_id' => 'city_world_id',
                    ],
                ],
                'deferrable' => [
                    11 => false,
                ],
                'unique' => [
                    11 => false,
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    5 => 'City_Hero',
                    'City_Faction',
                    10 => 'City_World',
                ],
                'targetEntity' => [
                    5 => 'App\\Entity\\Hero',
                    'App\\Entity\\Faction',
                    10 => 'App\\Entity\\World',
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Continent',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\ContinentRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Name' => $o[2],
                        'Description' => $o[3],
                        'Image_Continent' => $o[4],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'Name',
                        'description' => 'Description',
                        'image_continent' => 'Image_Continent',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Name' => 'name',
                        'Description' => 'description',
                        'Image_Continent' => 'image_continent',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'continent',
                    ],
                ],
                'associationMappings' => [
                    [
                        'Continent_Faction' => $o[5],
                        'Continent_Hero' => $o[6],
                        'Continent_Guild' => $o[7],
                        'Continent_World' => $o[8],
                    ],
                ],
                'idGenerator' => [
                    $o[10],
                ],
                'name' => [
                    'App\\Entity\\Continent',
                    9 => 'continent_world_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'text',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Name',
                    'Description',
                    'Image_Continent',
                ],
                'columnName' => [
                    1 => 'id',
                    'name',
                    'description',
                    'image_continent',
                ],
                'length' => [
                    2 => 255,
                    4 => 255,
                ],
                'nullable' => [
                    3 => true,
                    true,
                    9 => false,
                ],
                'fetch' => [
                    5 => 2,
                    2,
                    2,
                    2,
                ],
                'sourceEntity' => [
                    5 => 'App\\Entity\\Continent',
                    'App\\Entity\\Continent',
                    'App\\Entity\\Continent',
                    'App\\Entity\\Continent',
                ],
                'mappedBy' => [
                    5 => 'Faction_Continent',
                    'Hero_Continent',
                    'Guild_Continent',
                ],
                'inversedBy' => [
                    8 => 'World_Continent',
                ],
                'sourceToTargetKeyColumns' => [
                    8 => [
                        'continent_world_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    8 => [
                        'id' => 'continent_world_id',
                    ],
                ],
                'joinColumns' => [
                    8 => [
                        $o[9],
                    ],
                ],
                'joinColumnFieldNames' => [
                    8 => [
                        'continent_world_id' => 'continent_world_id',
                    ],
                ],
                'deferrable' => [
                    9 => false,
                ],
                'unique' => [
                    9 => false,
                ],
                'referencedColumnName' => [
                    9 => 'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    5 => 'Continent_Faction',
                    'Continent_Hero',
                    'Continent_Guild',
                    'Continent_World',
                ],
                'targetEntity' => [
                    5 => 'App\\Entity\\Faction',
                    'App\\Entity\\Hero',
                    'App\\Entity\\Guild',
                    'App\\Entity\\World',
                ],
            ],
        ],
        $o[0],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Domain',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\DomainRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Name' => $o[2],
                        'Type' => $o[3],
                        'Image_Domain' => $o[4],
                        'Description' => $o[5],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'Name',
                        'type' => 'Type',
                        'image_domain' => 'Image_Domain',
                        'description' => 'Description',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Name' => 'name',
                        'Type' => 'type',
                        'Image_Domain' => 'image_domain',
                        'Description' => 'description',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'domain',
                    ],
                ],
                'associationMappings' => [
                    [
                        'capacities' => $o[6],
                        'Heroes' => $o[7],
                        'Domain_Race' => $o[8],
                        'Domain_World' => $o[9],
                    ],
                ],
                'idGenerator' => [
                    $o[11],
                ],
                'name' => [
                    'App\\Entity\\Domain',
                    10 => 'domain_world_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'text',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Name',
                    'Type',
                    'Image_Domain',
                    'Description',
                ],
                'columnName' => [
                    1 => 'id',
                    'name',
                    'type',
                    'image_domain',
                    'description',
                ],
                'length' => [
                    2 => 255,
                    255,
                    255,
                ],
                'nullable' => [
                    3 => true,
                    true,
                    true,
                    10 => false,
                ],
                'fetch' => [
                    6 => 2,
                    2,
                    2,
                    2,
                ],
                'sourceEntity' => [
                    6 => 'App\\Entity\\Domain',
                    'App\\Entity\\Domain',
                    'App\\Entity\\Domain',
                    'App\\Entity\\Domain',
                ],
                'mappedBy' => [
                    6 => 'Domain',
                    'Hero_Domain',
                    'Race_Domain',
                ],
                'inversedBy' => [
                    9 => 'World_Domain',
                ],
                'sourceToTargetKeyColumns' => [
                    9 => [
                        'domain_world_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    9 => [
                        'id' => 'domain_world_id',
                    ],
                ],
                'joinColumns' => [
                    9 => [
                        $o[10],
                    ],
                ],
                'joinColumnFieldNames' => [
                    9 => [
                        'domain_world_id' => 'domain_world_id',
                    ],
                ],
                'deferrable' => [
                    10 => false,
                ],
                'unique' => [
                    10 => false,
                ],
                'referencedColumnName' => [
                    10 => 'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    6 => 'capacities',
                    'Heroes',
                    'Domain_Race',
                    'Domain_World',
                ],
                'targetEntity' => [
                    6 => 'App\\Entity\\Capacity',
                    'App\\Entity\\Hero',
                    'App\\Entity\\Race',
                    'App\\Entity\\World',
                ],
            ],
        ],
        $o[0],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinTableMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinTableMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinTableMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinTableMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinTableMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinTableMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Faction',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\FactionRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Name' => $o[2],
                        'Type' => $o[3],
                        'Regime' => $o[4],
                        'Image_Faction' => $o[5],
                        'Description' => $o[6],
                        'Emblem_Image' => $o[7],
                        'Couleur' => $o[8],
                        'Created_at' => $o[9],
                        'Capital' => $o[10],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'Name',
                        'type' => 'Type',
                        'regime' => 'Regime',
                        'image_faction' => 'Image_Faction',
                        'description' => 'Description',
                        'emblem_image' => 'Emblem_Image',
                        'couleur' => 'Couleur',
                        'created_at' => 'Created_at',
                        'capital' => 'Capital',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Name' => 'name',
                        'Type' => 'type',
                        'Regime' => 'regime',
                        'Image_Faction' => 'image_faction',
                        'Description' => 'description',
                        'Emblem_Image' => 'emblem_image',
                        'Couleur' => 'couleur',
                        'Created_at' => 'created_at',
                        'Capital' => 'capital',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'faction',
                    ],
                ],
                'associationMappings' => [
                    [
                        'Dirigeant_hero' => $o[11],
                        'Hero_Linked' => $o[15],
                        'Faction_Hero' => $o[19],
                        'Faction_City' => $o[20],
                        'Faction_Guild' => $o[24],
                        'Faction_Continent' => $o[28],
                        'Faction_World' => $o[32],
                    ],
                ],
                'idGenerator' => [
                    $o[34],
                ],
                'name' => [
                    'App\\Entity\\Faction',
                    12 => 'faction_dirigeant',
                    'faction_id',
                    'hero_id',
                    16 => 'faction_hero',
                    'faction_id',
                    'hero_id',
                    21 => 'faction_city',
                    'faction_id',
                    'city_id',
                    25 => 'faction_guild',
                    'faction_id',
                    'guild_id',
                    29 => 'faction_continent',
                    'faction_id',
                    'continent_id',
                    33 => 'faction_world_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                    'text',
                    'string',
                    'string',
                    'datetime',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Name',
                    'Type',
                    'Regime',
                    'Image_Faction',
                    'Description',
                    'Emblem_Image',
                    'Couleur',
                    'Created_at',
                    'Capital',
                ],
                'columnName' => [
                    1 => 'id',
                    'name',
                    'type',
                    'regime',
                    'image_faction',
                    'description',
                    'emblem_image',
                    'couleur',
                    'created_at',
                    'capital',
                ],
                'length' => [
                    2 => 255,
                    255,
                    255,
                    255,
                    7 => 255,
                    255,
                    10 => 255,
                ],
                'nullable' => [
                    3 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    33 => false,
                ],
                'fetch' => [
                    11 => 2,
                    15 => 2,
                    19 => 2,
                    2,
                    24 => 2,
                    28 => 2,
                    32 => 2,
                ],
                'isOnDeleteCascade' => [
                    11 => true,
                    15 => true,
                    20 => true,
                    24 => true,
                    28 => true,
                ],
                'sourceEntity' => [
                    11 => 'App\\Entity\\Faction',
                    15 => 'App\\Entity\\Faction',
                    19 => 'App\\Entity\\Faction',
                    'App\\Entity\\Faction',
                    24 => 'App\\Entity\\Faction',
                    28 => 'App\\Entity\\Faction',
                    32 => 'App\\Entity\\Faction',
                ],
                'inversedBy' => [
                    11 => 'Faction_Dirigeant',
                    15 => 'Faction_Linked',
                    20 => 'City_Faction',
                    24 => 'Guild_Faction',
                    28 => 'Continent_Faction',
                    32 => 'World_Faction',
                ],
                'joinTable' => [
                    11 => $o[12],
                    15 => $o[16],
                    20 => $o[21],
                    24 => $o[25],
                    28 => $o[29],
                ],
                'joinTableColumns' => [
                    11 => [
                        'faction_id',
                        'hero_id',
                    ],
                    15 => [
                        'faction_id',
                        'hero_id',
                    ],
                    20 => [
                        'faction_id',
                        'city_id',
                    ],
                    24 => [
                        'faction_id',
                        'guild_id',
                    ],
                    28 => [
                        'faction_id',
                        'continent_id',
                    ],
                ],
                'relationToSourceKeyColumns' => [
                    11 => [
                        'faction_id' => 'id',
                    ],
                    15 => [
                        'faction_id' => 'id',
                    ],
                    20 => [
                        'faction_id' => 'id',
                    ],
                    24 => [
                        'faction_id' => 'id',
                    ],
                    28 => [
                        'faction_id' => 'id',
                    ],
                ],
                'relationToTargetKeyColumns' => [
                    11 => [
                        'hero_id' => 'id',
                    ],
                    15 => [
                        'hero_id' => 'id',
                    ],
                    20 => [
                        'city_id' => 'id',
                    ],
                    24 => [
                        'guild_id' => 'id',
                    ],
                    28 => [
                        'continent_id' => 'id',
                    ],
                ],
                'joinColumns' => [
                    12 => [
                        $o[13],
                    ],
                    16 => [
                        $o[17],
                    ],
                    21 => [
                        $o[22],
                    ],
                    25 => [
                        $o[26],
                    ],
                    29 => [
                        $o[30],
                    ],
                    32 => [
                        $o[33],
                    ],
                ],
                'inverseJoinColumns' => [
                    12 => [
                        $o[14],
                    ],
                    16 => [
                        $o[18],
                    ],
                    21 => [
                        $o[23],
                    ],
                    25 => [
                        $o[27],
                    ],
                    29 => [
                        $o[31],
                    ],
                ],
                'onDelete' => [
                    13 => 'CASCADE',
                    'CASCADE',
                    17 => 'CASCADE',
                    'CASCADE',
                    22 => 'CASCADE',
                    'CASCADE',
                    26 => 'CASCADE',
                    'CASCADE',
                    30 => 'CASCADE',
                    'CASCADE',
                ],
                'referencedColumnName' => [
                    13 => 'id',
                    'id',
                    17 => 'id',
                    'id',
                    22 => 'id',
                    'id',
                    26 => 'id',
                    'id',
                    30 => 'id',
                    'id',
                    33 => 'id',
                ],
                'mappedBy' => [
                    19 => 'Hero_Faction',
                ],
                'sourceToTargetKeyColumns' => [
                    32 => [
                        'faction_world_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    32 => [
                        'id' => 'faction_world_id',
                    ],
                ],
                'joinColumnFieldNames' => [
                    32 => [
                        'faction_world_id' => 'faction_world_id',
                    ],
                ],
                'deferrable' => [
                    33 => false,
                ],
                'unique' => [
                    33 => false,
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    11 => 'Dirigeant_hero',
                    15 => 'Hero_Linked',
                    19 => 'Faction_Hero',
                    'Faction_City',
                    24 => 'Faction_Guild',
                    28 => 'Faction_Continent',
                    32 => 'Faction_World',
                ],
                'targetEntity' => [
                    11 => 'App\\Entity\\Hero',
                    15 => 'App\\Entity\\Hero',
                    19 => 'App\\Entity\\Hero',
                    'App\\Entity\\City',
                    24 => 'App\\Entity\\Guild',
                    28 => 'App\\Entity\\Continent',
                    32 => 'App\\Entity\\World',
                ],
            ],
        ],
        $o[0],
        []
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinTableMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinTableMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Guild',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\GuildRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Name' => $o[2],
                        'Type' => $o[3],
                        'Image_Guild' => $o[4],
                        'Description' => $o[5],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'Name',
                        'type' => 'Type',
                        'image_guild' => 'Image_Guild',
                        'description' => 'Description',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Name' => 'name',
                        'Type' => 'type',
                        'Image_Guild' => 'image_guild',
                        'Description' => 'description',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'guild',
                    ],
                ],
                'associationMappings' => [
                    [
                        'Visibility_id' => $o[6],
                        'Guild_Faction' => $o[8],
                        'Guild_Continent' => $o[9],
                        'Guild_World' => $o[13],
                        'heroes' => $o[14],
                    ],
                ],
                'idGenerator' => [
                    $o[15],
                ],
                'name' => [
                    'App\\Entity\\Guild',
                    7 => 'visibility_id_id',
                    10 => 'guild_continent',
                    'guild_id',
                    'continent_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Name',
                    'Type',
                    'Image_Guild',
                    'Description',
                ],
                'columnName' => [
                    1 => 'id',
                    'name',
                    'type',
                    'image_guild',
                    'description',
                ],
                'length' => [
                    2 => 255,
                    255,
                    255,
                    255,
                ],
                'nullable' => [
                    3 => true,
                    true,
                    true,
                ],
                'fetch' => [
                    6 => 2,
                    8 => 2,
                    2,
                    13 => 2,
                    2,
                ],
                'sourceEntity' => [
                    6 => 'App\\Entity\\Guild',
                    8 => 'App\\Entity\\Guild',
                    'App\\Entity\\Guild',
                    13 => 'App\\Entity\\Guild',
                    'App\\Entity\\Guild',
                ],
                'sourceToTargetKeyColumns' => [
                    6 => [
                        'visibility_id_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    6 => [
                        'id' => 'visibility_id_id',
                    ],
                ],
                'joinColumns' => [
                    6 => [
                        $o[7],
                    ],
                    10 => [
                        $o[11],
                    ],
                ],
                'joinColumnFieldNames' => [
                    6 => [
                        'visibility_id_id' => 'visibility_id_id',
                    ],
                ],
                'referencedColumnName' => [
                    7 => 'id',
                    11 => 'id',
                    'id',
                ],
                'mappedBy' => [
                    8 => 'Faction_Guild',
                    13 => 'World_Guild',
                    'guilds',
                ],
                'isOnDeleteCascade' => [
                    9 => true,
                ],
                'inversedBy' => [
                    9 => 'Continent_Guild',
                ],
                'joinTable' => [
                    9 => $o[10],
                ],
                'joinTableColumns' => [
                    9 => [
                        'guild_id',
                        'continent_id',
                    ],
                ],
                'relationToSourceKeyColumns' => [
                    9 => [
                        'guild_id' => 'id',
                    ],
                ],
                'relationToTargetKeyColumns' => [
                    9 => [
                        'continent_id' => 'id',
                    ],
                ],
                'inverseJoinColumns' => [
                    10 => [
                        $o[12],
                    ],
                ],
                'onDelete' => [
                    11 => 'CASCADE',
                    'CASCADE',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    6 => 'Visibility_id',
                    8 => 'Guild_Faction',
                    'Guild_Continent',
                    13 => 'Guild_World',
                    'heroes',
                ],
                'targetEntity' => [
                    6 => 'App\\Entity\\Visibility',
                    8 => 'App\\Entity\\Faction',
                    'App\\Entity\\Continent',
                    13 => 'App\\Entity\\World',
                    'App\\Entity\\Hero',
                ],
            ],
        ],
        $o[0],
        []
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinTableMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinTableMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinTableMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinTableMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinTableMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinTableMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinTableMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Hero',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\HeroRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Name' => $o[2],
                        'Age' => $o[3],
                        'Size' => $o[4],
                        'Image_Hero' => $o[5],
                        'Description' => $o[6],
                        'Fonction' => $o[7],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'Name',
                        'age' => 'Age',
                        'size' => 'Size',
                        'image_hero' => 'Image_Hero',
                        'description' => 'Description',
                        'fonction' => 'Fonction',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Name' => 'name',
                        'Age' => 'age',
                        'Size' => 'size',
                        'Image_Hero' => 'image_hero',
                        'Description' => 'description',
                        'Fonction' => 'fonction',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'hero',
                    ],
                ],
                'associationMappings' => [
                    [
                        'guilds' => $o[8],
                        'Faction_Dirigeant' => $o[12],
                        'Faction_Linked' => $o[13],
                        'Hero_Domain' => $o[14],
                        'Hero_Faction' => $o[18],
                        'Hero_Race' => $o[22],
                        'Hero_City' => $o[26],
                        'Hero_Continent' => $o[30],
                        'Hero_World' => $o[34],
                    ],
                ],
                'idGenerator' => [
                    $o[36],
                ],
                'name' => [
                    'App\\Entity\\Hero',
                    9 => 'hero_guild',
                    'hero_id',
                    'guild_id',
                    15 => 'hero_domain',
                    'hero_id',
                    'domain_id',
                    19 => 'hero_faction',
                    'hero_id',
                    'faction_id',
                    23 => 'hero_race',
                    'hero_id',
                    'race_id',
                    27 => 'hero_city',
                    'hero_id',
                    'city_id',
                    31 => 'hero_continent',
                    'hero_id',
                    'continent_id',
                    35 => 'hero_world_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                    'text',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Name',
                    'Age',
                    'Size',
                    'Image_Hero',
                    'Description',
                    'Fonction',
                ],
                'columnName' => [
                    1 => 'id',
                    'name',
                    'age',
                    'size',
                    'image_hero',
                    'description',
                    'fonction',
                ],
                'length' => [
                    2 => 255,
                    255,
                    255,
                    255,
                    7 => 255,
                ],
                'nullable' => [
                    3 => true,
                    5 => true,
                    true,
                    true,
                    35 => false,
                ],
                'fetch' => [
                    8 => 2,
                    12 => 2,
                    2,
                    2,
                    18 => 2,
                    22 => 2,
                    26 => 2,
                    30 => 2,
                    34 => 2,
                ],
                'isOnDeleteCascade' => [
                    8 => true,
                    14 => true,
                    18 => true,
                    22 => true,
                    26 => true,
                    30 => true,
                ],
                'sourceEntity' => [
                    8 => 'App\\Entity\\Hero',
                    12 => 'App\\Entity\\Hero',
                    'App\\Entity\\Hero',
                    'App\\Entity\\Hero',
                    18 => 'App\\Entity\\Hero',
                    22 => 'App\\Entity\\Hero',
                    26 => 'App\\Entity\\Hero',
                    30 => 'App\\Entity\\Hero',
                    34 => 'App\\Entity\\Hero',
                ],
                'inversedBy' => [
                    8 => 'heroes',
                    14 => 'Heroes',
                    18 => 'Faction_Hero',
                    22 => 'Race_Hero',
                    26 => 'City_Hero',
                    30 => 'Continent_Hero',
                    34 => 'World_Hero',
                ],
                'joinTable' => [
                    8 => $o[9],
                    14 => $o[15],
                    18 => $o[19],
                    22 => $o[23],
                    26 => $o[27],
                    30 => $o[31],
                ],
                'joinTableColumns' => [
                    8 => [
                        'hero_id',
                        'guild_id',
                    ],
                    14 => [
                        'hero_id',
                        'domain_id',
                    ],
                    18 => [
                        'hero_id',
                        'faction_id',
                    ],
                    22 => [
                        'hero_id',
                        'race_id',
                    ],
                    26 => [
                        'hero_id',
                        'city_id',
                    ],
                    30 => [
                        'hero_id',
                        'continent_id',
                    ],
                ],
                'relationToSourceKeyColumns' => [
                    8 => [
                        'hero_id' => 'id',
                    ],
                    14 => [
                        'hero_id' => 'id',
                    ],
                    18 => [
                        'hero_id' => 'id',
                    ],
                    22 => [
                        'hero_id' => 'id',
                    ],
                    26 => [
                        'hero_id' => 'id',
                    ],
                    30 => [
                        'hero_id' => 'id',
                    ],
                ],
                'relationToTargetKeyColumns' => [
                    8 => [
                        'guild_id' => 'id',
                    ],
                    14 => [
                        'domain_id' => 'id',
                    ],
                    18 => [
                        'faction_id' => 'id',
                    ],
                    22 => [
                        'race_id' => 'id',
                    ],
                    26 => [
                        'city_id' => 'id',
                    ],
                    30 => [
                        'continent_id' => 'id',
                    ],
                ],
                'joinColumns' => [
                    9 => [
                        $o[10],
                    ],
                    15 => [
                        $o[16],
                    ],
                    19 => [
                        $o[20],
                    ],
                    23 => [
                        $o[24],
                    ],
                    27 => [
                        $o[28],
                    ],
                    31 => [
                        $o[32],
                    ],
                    34 => [
                        $o[35],
                    ],
                ],
                'inverseJoinColumns' => [
                    9 => [
                        $o[11],
                    ],
                    15 => [
                        $o[17],
                    ],
                    19 => [
                        $o[21],
                    ],
                    23 => [
                        $o[25],
                    ],
                    27 => [
                        $o[29],
                    ],
                    31 => [
                        $o[33],
                    ],
                ],
                'onDelete' => [
                    10 => 'CASCADE',
                    'CASCADE',
                    16 => 'CASCADE',
                    'CASCADE',
                    20 => 'CASCADE',
                    'CASCADE',
                    24 => 'CASCADE',
                    'CASCADE',
                    28 => 'CASCADE',
                    'CASCADE',
                    32 => 'CASCADE',
                    'CASCADE',
                ],
                'referencedColumnName' => [
                    10 => 'id',
                    'id',
                    16 => 'id',
                    'id',
                    20 => 'id',
                    'id',
                    24 => 'id',
                    'id',
                    28 => 'id',
                    'id',
                    32 => 'id',
                    'id',
                    35 => 'id',
                ],
                'mappedBy' => [
                    12 => 'Dirigeant_hero',
                    'Hero_Linked',
                ],
                'sourceToTargetKeyColumns' => [
                    34 => [
                        'hero_world_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    34 => [
                        'id' => 'hero_world_id',
                    ],
                ],
                'joinColumnFieldNames' => [
                    34 => [
                        'hero_world_id' => 'hero_world_id',
                    ],
                ],
                'deferrable' => [
                    35 => false,
                ],
                'unique' => [
                    35 => false,
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    8 => 'guilds',
                    12 => 'Faction_Dirigeant',
                    'Faction_Linked',
                    'Hero_Domain',
                    18 => 'Hero_Faction',
                    22 => 'Hero_Race',
                    26 => 'Hero_City',
                    30 => 'Hero_Continent',
                    34 => 'Hero_World',
                ],
                'targetEntity' => [
                    8 => 'App\\Entity\\Guild',
                    12 => 'App\\Entity\\Faction',
                    'App\\Entity\\Faction',
                    'App\\Entity\\Domain',
                    18 => 'App\\Entity\\Faction',
                    22 => 'App\\Entity\\Race',
                    26 => 'App\\Entity\\City',
                    30 => 'App\\Entity\\Continent',
                    34 => 'App\\Entity\\World',
                ],
            ],
        ],
        $o[0],
        []
    );
},
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinTableMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinTableMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Race',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\RaceRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Name' => $o[2],
                        'Image_Race' => $o[3],
                        'Description' => $o[4],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'Name',
                        'image_race' => 'Image_Race',
                        'description' => 'Description',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Name' => 'name',
                        'Image_Race' => 'image_race',
                        'Description' => 'description',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'race',
                    ],
                ],
                'associationMappings' => [
                    [
                        'Race_Hero' => $o[5],
                        'Race_Domain' => $o[6],
                        'Race_World' => $o[10],
                    ],
                ],
                'idGenerator' => [
                    $o[12],
                ],
                'name' => [
                    'App\\Entity\\Race',
                    7 => 'race_domain',
                    'race_id',
                    'domain_id',
                    11 => 'race_world_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'text',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Name',
                    'Image_Race',
                    'Description',
                ],
                'columnName' => [
                    1 => 'id',
                    'name',
                    'image_race',
                    'description',
                ],
                'length' => [
                    2 => 255,
                    255,
                ],
                'nullable' => [
                    3 => true,
                    true,
                    11 => false,
                ],
                'fetch' => [
                    5 => 2,
                    2,
                    10 => 2,
                ],
                'sourceEntity' => [
                    5 => 'App\\Entity\\Race',
                    'App\\Entity\\Race',
                    10 => 'App\\Entity\\Race',
                ],
                'mappedBy' => [
                    5 => 'Hero_Race',
                ],
                'isOnDeleteCascade' => [
                    6 => true,
                ],
                'inversedBy' => [
                    6 => 'Domain_Race',
                    10 => 'World_Race',
                ],
                'joinTable' => [
                    6 => $o[7],
                ],
                'joinTableColumns' => [
                    6 => [
                        'race_id',
                        'domain_id',
                    ],
                ],
                'relationToSourceKeyColumns' => [
                    6 => [
                        'race_id' => 'id',
                    ],
                ],
                'relationToTargetKeyColumns' => [
                    6 => [
                        'domain_id' => 'id',
                    ],
                ],
                'joinColumns' => [
                    7 => [
                        $o[8],
                    ],
                    10 => [
                        $o[11],
                    ],
                ],
                'inverseJoinColumns' => [
                    7 => [
                        $o[9],
                    ],
                ],
                'onDelete' => [
                    8 => 'CASCADE',
                    'CASCADE',
                ],
                'referencedColumnName' => [
                    8 => 'id',
                    'id',
                    11 => 'id',
                ],
                'sourceToTargetKeyColumns' => [
                    10 => [
                        'race_world_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    10 => [
                        'id' => 'race_world_id',
                    ],
                ],
                'joinColumnFieldNames' => [
                    10 => [
                        'race_world_id' => 'race_world_id',
                    ],
                ],
                'deferrable' => [
                    11 => false,
                ],
                'unique' => [
                    11 => false,
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    5 => 'Race_Hero',
                    'Race_Domain',
                    10 => 'Race_World',
                ],
                'targetEntity' => [
                    5 => 'App\\Entity\\Hero',
                    'App\\Entity\\Domain',
                    10 => 'App\\Entity\\World',
                ],
            ],
        ],
        $o[0],
        []
    );
},
8 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinTableMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinTableMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinTableMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\World',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\WorldRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Name' => $o[2],
                        'Description' => $o[3],
                        'Worldimage' => $o[4],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'Name',
                        'description' => 'Description',
                        'worldimage' => 'Worldimage',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Name' => 'name',
                        'Description' => 'description',
                        'Worldimage' => 'worldimage',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'world',
                    ],
                ],
                'associationMappings' => [
                    [
                        'users' => $o[5],
                        'World_Guild' => $o[9],
                        'World_Faction' => $o[13],
                        'World_Capacity' => $o[14],
                        'World_City' => $o[15],
                        'World_Continent' => $o[16],
                        'World_Hero' => $o[17],
                        'World_Domain' => $o[18],
                        'World_Race' => $o[19],
                    ],
                ],
                'idGenerator' => [
                    $o[20],
                ],
                'name' => [
                    'App\\Entity\\World',
                    6 => 'world_user',
                    'world_id',
                    'user_id',
                    10 => 'world_guild',
                    'world_id',
                    'guild_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'text',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Name',
                    'Description',
                    'Worldimage',
                ],
                'columnName' => [
                    1 => 'id',
                    'name',
                    'description',
                    'worldimage',
                ],
                'length' => [
                    2 => 255,
                    4 => 255,
                ],
                'nullable' => [
                    3 => true,
                    true,
                ],
                'fetch' => [
                    5 => 2,
                    9 => 2,
                    13 => 2,
                    2,
                    2,
                    2,
                    2,
                    2,
                    2,
                ],
                'isOnDeleteCascade' => [
                    5 => true,
                    9 => true,
                ],
                'sourceEntity' => [
                    5 => 'App\\Entity\\World',
                    9 => 'App\\Entity\\World',
                    13 => 'App\\Entity\\World',
                    'App\\Entity\\World',
                    'App\\Entity\\World',
                    'App\\Entity\\World',
                    'App\\Entity\\World',
                    'App\\Entity\\World',
                    'App\\Entity\\World',
                ],
                'inversedBy' => [
                    5 => 'worlds',
                    9 => 'Guild_World',
                ],
                'joinTable' => [
                    5 => $o[6],
                    9 => $o[10],
                ],
                'joinTableColumns' => [
                    5 => [
                        'world_id',
                        'user_id',
                    ],
                    9 => [
                        'world_id',
                        'guild_id',
                    ],
                ],
                'relationToSourceKeyColumns' => [
                    5 => [
                        'world_id' => 'id',
                    ],
                    9 => [
                        'world_id' => 'id',
                    ],
                ],
                'relationToTargetKeyColumns' => [
                    5 => [
                        'user_id' => 'id',
                    ],
                    9 => [
                        'guild_id' => 'id',
                    ],
                ],
                'joinColumns' => [
                    6 => [
                        $o[7],
                    ],
                    10 => [
                        $o[11],
                    ],
                ],
                'inverseJoinColumns' => [
                    6 => [
                        $o[8],
                    ],
                    10 => [
                        $o[12],
                    ],
                ],
                'onDelete' => [
                    7 => 'CASCADE',
                    'CASCADE',
                    11 => 'CASCADE',
                    'CASCADE',
                ],
                'referencedColumnName' => [
                    7 => 'id',
                    'id',
                    11 => 'id',
                    'id',
                ],
                'mappedBy' => [
                    13 => 'Faction_World',
                    'Capacity_world',
                    'City_World',
                    'Continent_World',
                    'Hero_World',
                    'Domain_World',
                    'Race_World',
                ],
                'cascade' => [
                    14 => [
                        'remove',
                    ],
                    [
                        'remove',
                    ],
                    [
                        'remove',
                    ],
                    [
                        'remove',
                    ],
                    [
                        'remove',
                    ],
                    [
                        'remove',
                    ],
                ],
                'orphanRemoval' => [
                    14 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    5 => 'users',
                    9 => 'World_Guild',
                    13 => 'World_Faction',
                    'World_Capacity',
                    'World_City',
                    'World_Continent',
                    'World_Hero',
                    'World_Domain',
                    'World_Race',
                ],
                'targetEntity' => [
                    5 => 'App\\Entity\\User',
                    9 => 'App\\Entity\\Guild',
                    13 => 'App\\Entity\\Faction',
                    'App\\Entity\\Capacity',
                    'App\\Entity\\City',
                    'App\\Entity\\Continent',
                    'App\\Entity\\Hero',
                    'App\\Entity\\Domain',
                    'App\\Entity\\Race',
                ],
            ],
        ],
        $o[0],
        []
    );
},
9 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Visibility',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\VisibilityRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Visibility' => $o[2],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'visibility' => 'Visibility',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Visibility' => 'visibility',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'visibility',
                    ],
                ],
                'idGenerator' => [
                    $o[3],
                ],
                'name' => [
                    'App\\Entity\\Visibility',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Visibility',
                ],
                'columnName' => [
                    1 => 'id',
                    'visibility',
                ],
                'length' => [
                    2 => 255,
                ],
                'nullable' => [
                    2 => true,
                ],
            ],
        ],
        $o[0],
        []
    );
},
10 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\User',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\UserRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'username' => $o[2],
                        'password' => $o[3],
                        'email' => $o[4],
                        'roles' => $o[5],
                        'profileImage' => $o[6],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'username' => 'username',
                        'password' => 'password',
                        'email' => 'email',
                        'roles' => 'roles',
                        'profile_image' => 'profileImage',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'username' => 'username',
                        'password' => 'password',
                        'email' => 'email',
                        'roles' => 'roles',
                        'profileImage' => 'profile_image',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'user',
                    ],
                ],
                'associationMappings' => [
                    [
                        'worlds' => $o[7],
                    ],
                ],
                'idGenerator' => [
                    $o[8],
                ],
                'name' => [
                    'App\\Entity\\User',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'json',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'username',
                    'password',
                    'email',
                    'roles',
                    'profileImage',
                ],
                'columnName' => [
                    1 => 'id',
                    'username',
                    'password',
                    'email',
                    'roles',
                    'profile_image',
                ],
                'length' => [
                    2 => 255,
                    255,
                    255,
                    6 => 255,
                ],
                'unique' => [
                    2 => true,
                    4 => true,
                ],
                'nullable' => [
                    6 => true,
                ],
                'fetch' => [
                    7 => 2,
                ],
                'sourceEntity' => [
                    7 => 'App\\Entity\\User',
                ],
                'mappedBy' => [
                    7 => 'users',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    7 => 'worlds',
                ],
                'targetEntity' => [
                    7 => 'App\\Entity\\World',
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
