<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUFQ1KCQ\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUFQ1KCQ/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerUFQ1KCQ.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerUFQ1KCQ\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerUFQ1KCQ\App_KernelProdContainer([
    'container.build_hash' => 'UFQ1KCQ',
    'container.build_id' => 'd73af55d',
    'container.build_time' => 1751353916,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUFQ1KCQ');
