<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8DmEdPW\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8DmEdPW/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container8DmEdPW.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container8DmEdPW\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container8DmEdPW\App_KernelProdContainer([
    'container.build_hash' => '8DmEdPW',
    'container.build_id' => '350c1f69',
    'container.build_time' => 1751351781,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8DmEdPW');
