<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQiz6J7j\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQiz6J7j/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQiz6J7j.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQiz6J7j\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQiz6J7j\App_KernelProdContainer([
    'container.build_hash' => 'Qiz6J7j',
    'container.build_id' => 'a304fa5f',
    'container.build_time' => 1748798801,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQiz6J7j');
