<?php

namespace ContainerEgWAoAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QMKxEMoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QMKxEMo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QMKxEMo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'guild' => ['privates', '.errored..service_locator.QMKxEMo.App\\Entity\\Guild', NULL, 'Cannot autowire service ".service_locator.QMKxEMo": it needs an instance of "App\\Entity\\Guild" but this type has been excluded in "config/services.yaml".'],
        ], [
            'guild' => 'App\\Entity\\Guild',
        ]);
    }
}
