<?php

namespace ContainerEgWAoAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lc6GHvCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lc6GHvC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Lc6GHvC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'capacityRepo' => ['privates', 'App\\Repository\\CapacityRepository', 'getCapacityRepositoryService', true],
            'worldRepo' => ['privates', 'App\\Repository\\WorldRepository', 'getWorldRepositoryService', false],
        ], [
            'capacityRepo' => 'App\\Repository\\CapacityRepository',
            'worldRepo' => 'App\\Repository\\WorldRepository',
        ]);
    }
}
