<?php

namespace ContainerEgWAoAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qisw8u4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Qisw8u4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Qisw8u4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'guildRepo' => ['privates', 'App\\Repository\\GuildRepository', 'getGuildRepositoryService', true],
            'worldRepo' => ['privates', 'App\\Repository\\WorldRepository', 'getWorldRepositoryService', false],
        ], [
            'guildRepo' => 'App\\Repository\\GuildRepository',
            'worldRepo' => 'App\\Repository\\WorldRepository',
        ]);
    }
}
