<?php

namespace ContainerEgWAoAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SLOOwjiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SLOOwji' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SLOOwji'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cityRepository' => ['privates', 'App\\Repository\\CityRepository', 'getCityRepositoryService', true],
            'worldRepo' => ['privates', 'App\\Repository\\WorldRepository', 'getWorldRepositoryService', false],
        ], [
            'cityRepository' => 'App\\Repository\\CityRepository',
            'worldRepo' => 'App\\Repository\\WorldRepository',
        ]);
    }
}
