<?php

namespace ContainerEgWAoAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UeVkhy8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UeVkhy8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UeVkhy8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'domain' => ['privates', '.errored..service_locator.UeVkhy8.App\\Entity\\Domain', NULL, 'Cannot autowire service ".service_locator.UeVkhy8": it needs an instance of "App\\Entity\\Domain" but this type has been excluded in "config/services.yaml".'],
        ], [
            'domain' => 'App\\Entity\\Domain',
        ]);
    }
}
