<?php

namespace ContainerEgWAoAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OlQu9PfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.olQu9Pf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.olQu9Pf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'factionRepo' => ['privates', 'App\\Repository\\FactionRepository', 'getFactionRepositoryService', true],
            'worldRepo' => ['privates', 'App\\Repository\\WorldRepository', 'getWorldRepositoryService', false],
        ], [
            'factionRepo' => 'App\\Repository\\FactionRepository',
            'worldRepo' => 'App\\Repository\\WorldRepository',
        ]);
    }
}
