<?php

namespace ContainerEgWAoAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContinent2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.v7U0tqL.App\Entity\Continent' shared service.
     *
     * @return \App\Entity\Continent
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.v7U0tqL": it needs an instance of "App\\Entity\\Continent" but this type has been excluded in "config/services.yaml".');
    }
}
