<?php

namespace ContainerEgWAoAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHeroRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\HeroRepository' shared autowired service.
     *
     * @return \App\Repository\HeroRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'HeroRepository.php';

        return $container->privates['App\\Repository\\HeroRepository'] = new \App\Repository\HeroRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
