<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class World extends \App\Entity\World implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Description' => [parent::class, 'Description', null, 16],
        "\0".parent::class."\0".'Name' => [parent::class, 'Name', null, 16],
        "\0".parent::class."\0".'World_Capacity' => [parent::class, 'World_Capacity', null, 16],
        "\0".parent::class."\0".'World_City' => [parent::class, 'World_City', null, 16],
        "\0".parent::class."\0".'World_Continent' => [parent::class, 'World_Continent', null, 16],
        "\0".parent::class."\0".'World_Domain' => [parent::class, 'World_Domain', null, 16],
        "\0".parent::class."\0".'World_Faction' => [parent::class, 'World_Faction', null, 16],
        "\0".parent::class."\0".'World_Guild' => [parent::class, 'World_Guild', null, 16],
        "\0".parent::class."\0".'World_Hero' => [parent::class, 'World_Hero', null, 16],
        "\0".parent::class."\0".'World_Race' => [parent::class, 'World_Race', null, 16],
        "\0".parent::class."\0".'Worldimage' => [parent::class, 'Worldimage', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'users' => [parent::class, 'users', null, 16],
        'Description' => [parent::class, 'Description', null, 16],
        'Name' => [parent::class, 'Name', null, 16],
        'World_Capacity' => [parent::class, 'World_Capacity', null, 16],
        'World_City' => [parent::class, 'World_City', null, 16],
        'World_Continent' => [parent::class, 'World_Continent', null, 16],
        'World_Domain' => [parent::class, 'World_Domain', null, 16],
        'World_Faction' => [parent::class, 'World_Faction', null, 16],
        'World_Guild' => [parent::class, 'World_Guild', null, 16],
        'World_Hero' => [parent::class, 'World_Hero', null, 16],
        'World_Race' => [parent::class, 'World_Race', null, 16],
        'Worldimage' => [parent::class, 'Worldimage', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'users' => [parent::class, 'users', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
