<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOBCB4x4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOBCB4x4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOBCB4x4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOBCB4x4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOBCB4x4\App_KernelDevDebugContainer([
    'container.build_hash' => 'OBCB4x4',
    'container.build_id' => '51746cfa',
    'container.build_time' => 1751225009,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOBCB4x4');
