<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLDNlqaW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLDNlqaW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLDNlqaW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLDNlqaW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLDNlqaW\App_KernelDevDebugContainer([
    'container.build_hash' => 'LDNlqaW',
    'container.build_id' => '0299bdd1',
    'container.build_time' => 1753456824,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLDNlqaW');
