<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPKldM14\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPKldM14/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPKldM14.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPKldM14\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPKldM14\App_KernelDevDebugContainer([
    'container.build_hash' => 'PKldM14',
    'container.build_id' => '1b23aeda',
    'container.build_time' => 1750789455,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPKldM14');
