<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class City extends \App\Entity\City implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'City_Faction' => [parent::class, 'City_Faction', null, 16],
        "\0".parent::class."\0".'City_Hero' => [parent::class, 'City_Hero', null, 16],
        "\0".parent::class."\0".'City_World' => [parent::class, 'City_World', null, 16],
        "\0".parent::class."\0".'Description' => [parent::class, 'Description', null, 16],
        "\0".parent::class."\0".'Image_City' => [parent::class, 'Image_City', null, 16],
        "\0".parent::class."\0".'Name' => [parent::class, 'Name', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        'City_Faction' => [parent::class, 'City_Faction', null, 16],
        'City_Hero' => [parent::class, 'City_Hero', null, 16],
        'City_World' => [parent::class, 'City_World', null, 16],
        'Description' => [parent::class, 'Description', null, 16],
        'Image_City' => [parent::class, 'Image_City', null, 16],
        'Name' => [parent::class, 'Name', null, 16],
        'id' => [parent::class, 'id', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
