<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Domain extends \App\Entity\Domain implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Description' => [parent::class, 'Description', null],
        "\0".parent::class."\0".'Domain_Race' => [parent::class, 'Domain_Race', null],
        "\0".parent::class."\0".'Domain_World' => [parent::class, 'Domain_World', null],
        "\0".parent::class."\0".'Heroes' => [parent::class, 'Heroes', null],
        "\0".parent::class."\0".'Image_Domain' => [parent::class, 'Image_Domain', null],
        "\0".parent::class."\0".'Name' => [parent::class, 'Name', null],
        "\0".parent::class."\0".'Type' => [parent::class, 'Type', null],
        "\0".parent::class."\0".'capacities' => [parent::class, 'capacities', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        'Description' => [parent::class, 'Description', null],
        'Domain_Race' => [parent::class, 'Domain_Race', null],
        'Domain_World' => [parent::class, 'Domain_World', null],
        'Heroes' => [parent::class, 'Heroes', null],
        'Image_Domain' => [parent::class, 'Image_Domain', null],
        'Name' => [parent::class, 'Name', null],
        'Type' => [parent::class, 'Type', null],
        'capacities' => [parent::class, 'capacities', null],
        'id' => [parent::class, 'id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
