<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Race extends \App\Entity\Race implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Description' => [parent::class, 'Description', null],
        "\0".parent::class."\0".'Image_Race' => [parent::class, 'Image_Race', null],
        "\0".parent::class."\0".'Name' => [parent::class, 'Name', null],
        "\0".parent::class."\0".'Race_Domain' => [parent::class, 'Race_Domain', null],
        "\0".parent::class."\0".'Race_Hero' => [parent::class, 'Race_Hero', null],
        "\0".parent::class."\0".'Race_World' => [parent::class, 'Race_World', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        'Description' => [parent::class, 'Description', null],
        'Image_Race' => [parent::class, 'Image_Race', null],
        'Name' => [parent::class, 'Name', null],
        'Race_Domain' => [parent::class, 'Race_Domain', null],
        'Race_Hero' => [parent::class, 'Race_Hero', null],
        'Race_World' => [parent::class, 'Race_World', null],
        'id' => [parent::class, 'id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
