<?php

namespace ContainerJxkt3Fv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XDVJ_33Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xDVJ.33' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xDVJ.33'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'guild' => ['privates', '.errored..service_locator.xDVJ.33.App\\Entity\\Guild', NULL, 'Cannot autowire service ".service_locator.xDVJ.33": it needs an instance of "App\\Entity\\Guild" but this type has been excluded in "config/services.yaml".'],
            'imageResizer' => ['privates', 'App\\Service\\ImageResizerService', 'getImageResizerServiceService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'em' => '?',
            'guild' => 'App\\Entity\\Guild',
            'imageResizer' => 'App\\Service\\ImageResizerService',
            'slugger' => '?',
        ]);
    }
}
