<?php

namespace ContainerJxkt3Fv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFactionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3iFfYLh.App\Entity\Faction' shared service.
     *
     * @return \App\Entity\Faction
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3iFfYLh": it needs an instance of "App\\Entity\\Faction" but this type has been excluded in "config/services.yaml".');
    }
}
