<?php

namespace ContainerJxkt3Fv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuild2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mx78Xy7.App\Entity\Guild' shared service.
     *
     * @return \App\Entity\Guild
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.mx78Xy7": it needs an instance of "App\\Entity\\Guild" but this type has been excluded in "config/services.yaml".');
    }
}
